### ISSUE TITLE
Link to Travis CI Results in 404

### ISSUE THREAD

**Issue by Weltraumschaf** [dracoon/dracoon-javascript-crypto-sdk#1]
The link of the build patch (https://travis-ci.com/dracoon) results in 404:

<img width="1404" alt="Screenshot 2022-08-04 at 21 25 24" src="https://user-images.githubusercontent.com/113232/182936475-b5eb0d11-6d07-4483-9d12-2df9070c0c33.png">

**Comment by StefanEyerer** [comment]
Thank you very much for reporting. This issue will be fixed shortly.

**Comment by StefanEyerer** [comment]
Issue has been fixed. Travis CI badge has been replaced by Github actions badge.
